services:
  play_pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: play_pgadmin
    restart: unless-stopped
    ports:
      - ${PLAY_PGADMIN_HTTP_PORT}:80
      - ${PLAY_PGADMIN_HTTPS_PORT}:443
    env_file:
      - .env
    networks:
      play_network:
        ipv4_address: ${PLAY_PGADMIN_IP_ADDRESS}

networks:
  play_network:
    name: play_network
    driver: bridge
    external: true
    ipam:
     config:
      - subnet: ${PLAY_NETWORK_SUBNET}
      - gateway: ${PLAY_NETWORK_GATEWAY}
