quiet: false
with-expecter: true
disable-version-string: true
dir: 'mocks/{{trimPrefix .PackagePath "github.com/reshifr/play/"}}'
mockname: '{{trimPrefix .InterfaceName "I"}}'
filename: '{{lower (trimPrefix .InterfaceName "I")}}.go'
outpkg: "{{.PackageName}}_mock"
packages:
  github.com/reshifr/play/core:
    interfaces:
      IEnv:
      ICmd:
      ICmdError:
      ICSPRNG:
  github.com/reshifr/play/core/codec:
    interfaces:
      IFFmpeg:
  github.com/reshifr/play/core/crypt:
    interfaces:
      IPad:
