services:
  play_postgresql0:
    image: postgres:16.2
    container_name: play_postgresql0
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - init/postgresql/.env
    volumes:
      - ${PLAY_POSTGRESQL_VOLUME0}:/var/lib/postgresql/data
    networks:
      play_network:
        ipv4_address: ${PLAY_POSTGRESQL_IP_ADDRESS0}

  play_postgresql1:
    image: postgres:16.2
    container_name: play_postgresql1
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - init/postgresql/.env
    volumes:
      - ${PLAY_POSTGRESQL_VOLUME1}:/var/lib/postgresql/data
    networks:
      play_network:
        ipv4_address: ${PLAY_POSTGRESQL_IP_ADDRESS1}

  # play_minio:
  #   image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
  #   container_name: play_minio
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   env_file:
  #     - .env
  #   networks:
  #     play_network:
  #       ipv4_address: ${PLAY_MINIO_IP_ADDRESS}
  #   volumes:
  #     - ${PLAY_MINIO_VOLUME}:/data
  #   command: server /data --console-address :9001

  play_db_init:
    image: reshifr/play/db/init:1.0
    build:
      context: init
      dockerfile: Dockerfile
    container_name: play_db_init
    restart: unless-stopped
    env_file:
      - .env
      - init/postgresql/.env
    networks:
      play_network:
        ipv4_address: ${PLAY_DB_INIT_IP_ADDRESS}
    depends_on:
      - play_postgresql0
      - play_postgresql1
      # - play_minio

networks:
  play_network:
    name: play_network
    driver: bridge
    external: true
    ipam:
     config:
      - subnet: ${PLAY_NETWORK_SUBNET}
      - gateway: ${PLAY_NETWORK_GATEWAY}
