services:
  play_admin:
    image: reshifr/play_admin:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: play_admin
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      play_network:
        ipv4_address: ${PLAY_ADMIN_IP_ADDRESS}

  play_postgresql0:
    image: postgres:16.2
    container_name: play_postgresql0
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ${PLAY_POSTGRESQL_VOLUME0}:/var/lib/postgresql/data
    networks:
      play_network:
        ipv4_address: ${PLAY_POSTGRESQL_IP_ADDRESS0}

  play_postgresql1:
    image: postgres:16.2
    container_name: play_postgresql1
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ${PLAY_POSTGRESQL_VOLUME1}:/var/lib/postgresql/data
    networks:
      play_network:
        ipv4_address: ${PLAY_POSTGRESQL_IP_ADDRESS1}

  play_minio:
    image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
    container_name: play_minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    networks:
      play_network:
        ipv4_address: ${PLAY_MINIO_IP_ADDRESS}
    volumes:
      - ${PLAY_MINIO_VOLUME}:/data
    command: server /data --console-address :9001

networks:
  play_network:
    name: play_network
    driver: bridge
    ipam:
     config:
       - subnet: ${PLAY_NETWORK_SUBNET}
         gateway: ${PLAY_NETWORK_GATEWAY}